# Generated by Django 3.0.7 on 2022-03-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='description',
            new_name='fb_description',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='purchase_date',
            new_name='mtg_date',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='name',
            new_name='mtg_with',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='cell_phone',
            new_name='task_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='city',
            new_name='task_number',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='task_priority',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='acquired_date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='acquired_value',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='recent_date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='recent_value',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='task',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='address',
        ),
        migrations.RemoveField(
            model_name='task',
            name='cust_number',
        ),
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
        migrations.RemoveField(
            model_name='task',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='feedback',
            name='fb_from',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='mtg_description',
            field=models.CharField(default='d', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
